name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: change to CAD directory
      run: cd CAD
    - name: create build directory
      run: mkdir build
    - name: change to build directory
      run: cd build
    - name: cmake
      run: cmake ..
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
