name: Build When Repository Changed

on: [push]

jobs:
  build:
    if: (false)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: dependencies
      run: sudo apt-get install libboost-python-dev python-dev freeglut3-dev
    - name: configure
      run: cd CAD && mkdir build && cd build && cmake ..
    - name: build
      run: cd CAD/build && make
  windows_build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: cd CAD && mkdir build && cd build && cmake ..
      shell: bash
    - name: build using MSBuild
      run: cd CAD/build && "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/MSBuild/Current/Bin/MSBuild.exe" cad.sln //p:Configuration=Release //p:Platform="x64"
      shell: bash
    - name: ls to see if the .dll was made
      run: cd CAD/build/Release && ls
      shell: bash
