name: Build When Repository Changed

on: [push]

jobs:
  build:
    if: (false)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: dependencies
      run: sudo apt-get install libboost-python-dev python-dev freeglut3-dev
    - name: configure
      run: cd CAD && mkdir build && cd build && cmake ..
    - name: build
      run: cd CAD/build && make
  windows_build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
      if: (false)
    - name: configure
      if: (false)
      run: cd CAD && mkdir build && cd build && cmake ..
      shell: bash
    - name: try devenv sln
      if: (false)
      run: cd CAD/build && dir && "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/IDE/devenv" /build "Release|Win32" cad.sln
      shell: bash
    - name: look
      run: cd "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.23.28105/bin/Hostx64/x64" && dir
      shell: bash
    - name: look2
      run: cd "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.23.28105/bin/Hostx64" && dir
      shell: bash
    - name: look3
      run: cd "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.23.28105/bin" && dir
      shell: bash
    - name: look4
      run: cd "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.23.28105" && dir
      shell: bash

