name: Build When Repository Changed

on: [push]

jobs:
  build:
    if: (false)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: dependencies
      run: sudo apt-get install libboost-python-dev python-dev freeglut3-dev
    - name: configure
      run: cd CAD && mkdir build && cd build && cmake ..
    - name: build
      run: cd CAD/build && make
  windows_build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: cd CAD && mkdir build && cd build && cmake ..
      shell: bash
    - name: look for dev
      run: cd C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.23.28105/bin/Hostx64/x64/ && dir
      shell: bash
    - name: build
      run: cd CAD && cd build && make
      shell: bash
