name: On Release Created

on:
  release:
    types: [created]
jobs:
  ubuntu_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: dependencies
      run: sudo apt-get install libboost-python-dev python-dev freeglut3-dev
    - name: configure
      run: cd CAD && mkdir build && cd build && cmake ..
    - name: build
      run: cd CAD/build && make
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: cd CAD/build/cad.so
        asset_name: cad.so
        tag: ${{ github.ref }}
        overwrite: true
  windows_build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: cd CAD && mkdir build && cd build && cmake ..
      shell: bash
    - name: build using MSBuild
      run: cd CAD/build && "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/MSBuild/Current/Bin/MSBuild.exe" cad.sln //p:Configuration=Release //p:Platform="x64"
      shell: bash
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: cd CAD/build/Release/cad.dll
        asset_name: cad.dll
        tag: ${{ github.ref }}
        overwrite: true